apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  profile: default
  components:
    cni:
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
