services:
  asmcli:
    container_name: asmcli-runner
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - lang=C
      - ver=1.23
    working_dir: /home/asm
    volumes:
      - ./asm-output:/home/asm/output
    networks:
      - default

networks:
  default:
    driver: bridge
