services:
  asmcli:
    container_name: asmcli-runner
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        lang: C.UTF-8
        ver: 1.23
        credentials: /tmp/keys/sa.json
        HPATH: /home/asm/
    env_file:
      - asmcli.env
    environment:
      - TZ Asia/Tokyo
    working_dir: /home/asm
    volumes:
      - ./asm-output:/home/asm/output
      - ./keys:/tmp/keys
    networks:
      - default
networks:
  default:
    driver: bridge