services:
  asmcli:
    container_name: asmcli-runner
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        lang: C.UTF-8
        ver: 1.23
        credentials: ${HPATH}.config/gcloud/application_default_credentials.json
        HPATH: $HPATH
    env_file:
      - asmcli.env
    environment:
      - TZ Asia/Tokyo
    working_dir: $HPATH
    volumes:
      - ./asm-output:${HPATH}${OUTPUT_DIR}
      - ./keys:/tmp/keys
      - $CREDENTIAL_PATH:${HPATH}.config/gcloud/application_default_credentials.json
    networks:
      - default
networks:
  default:
    driver: bridge