services:
  asmcli:
    container_name: asmcli-runner
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        lang: "C.UTF-8"
        ver: 1.23
        credentials: "${HPATH}/.config/gcloud/"
        hpath: "${HPATH}/"
        jsonfile: "application_default_credentials.json"
    env_file:
      - asmcli.env
    environment:
      - TZ Asia/Tokyo
    working_dir: "${HPATH}"
    volumes:
      - ./asm-output:"${HPATH}${OUTPUT_DIR}"
      - ./keys:/tmp/keys
    networks:
      - default
networks:
  default:
    driver: bridge