---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: handson-gateway
  namespace: handson
spec:
  selector:
    istio: ingressgateway
    app: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http-app
      protocol: HTTP
    hosts:
    - "csm.handson.com"