---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: handson-gateway
  namespace: handson
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8880
      name: http-app
      protocol: HTTP
    hosts:
    - "csm.handson.com"