---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: handson-gateway
  namespace: handson
spec:
  servers:
  - port:
      number: 18080
      name: http
      protocol: HTTP
    hosts:
    - csm.handson.com